stages:
  - build
  - deploy

# Job zum Abrufen des Repository-Codes und Bauen der Hugo-Seite
build:
  stage: build
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm git go hugo python git-lfs
    - git lfs install
  script:
    - hugo mod get
    - hugo mod tidy
    - hugo --gc --minify --enableGitInfo
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main"'

#  Job zum Bereitstellen der Dateien via SSH mit Passwort
deploy:
  stage: deploy
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm openssh sshpass rsync
  script:
    - |
      echo "Entferne alte Dateien auf dem Server..."
      sshpass -p "$isvpass" ssh -o StrictHostKeyChecking=no "webuser@$DEPLOY_HOST" "rm -rf /var/www/adventskalender/*"

      echo "Lade neue Dateien hoch..."
      sshpass -p "$isvpass" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" public/ "webuser@$DEPLOY_HOST:/var/www/adventskalender/"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
