title = "Advent of Chess"
baseURL = "https://adventskalender.ilmenauer-schachverein.de"

defaultContentLanguage = 'de'

[languages]
  [languages.de]
  languageName = "German / Deutsch"
  weight = 0
  title = "Schach Adventskalender"
  contentDir = "content/de"
  languageCode = "de"
  
  [languages.en]
  languageName = "Englisch / English"
  weight = 1
  title = " Advent of Chess"
  contentDir = "content/en"
  languageCode = "en"


# Import hextra as module
[module]
  [[module.imports]]
  path = "github.com/imfing/hextra"

[markup]
  # Allow raw HTML
  [markup.goldmark.renderer]
  unsafe = true

  [markup.goldmark.extensions]
  footnote = true

  # Enable hextra syntax highlight
  [markup.highlight]
  noClasses = false
  
[menu]
  [[menu.main]]
  name = "Search"
  weight = 5
  [menu.main.params]
  type = "search"

  [[menu.main]]
  name = "Gitlab"
  weight = 6
  url = "https://github.com/IlmenauerSchachverein/Adventskalender"
  [menu.main.params]
  icon = "github"

  [[menu.main]]
  name = "Instagram"
  weight = 7
  url = "https://instagram.com/ilmenauer_schachverein"
  [menu.main.params]
  icon = "instagram"

[params]
  disableToc = true

  [params.navbar]
  displayTitle = true
  displayLogo = true

  [params.theme]
  default = "system"

  [params.footer]
  displayCopyright = false
  displayPoweredBy = false

  [params.editURL]
  enable = false
  # base = "https://github.com/eskopp/AdventofChess/edit/content/main/" # outdated

  [params.page]
  width = "full"
